webtalk_init -webtalk_dir E:/elektronika-notatki/Rok_IV/SDUP/SDUP-FPGA/Lab7/CordicOpt/CordicOpt.sim/sim_1/impl/timing/xsim/xsim.dir/cordic_rtl_TB_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 28 19:17:55 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4c939c75-3c80-4b47-bb10-25c5dbd81b91" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f883c5340f2848638bff6a950e1c911b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "14" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.41_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "13976_KB" -context "xsim\\usage"
webtalk_transmit -clientid 790945835 -regid "" -xml E:/elektronika-notatki/Rok_IV/SDUP/SDUP-FPGA/Lab7/CordicOpt/CordicOpt.sim/sim_1/impl/timing/xsim/xsim.dir/cordic_rtl_TB_time_impl/webtalk/usage_statistics_ext_xsim.xml -html E:/elektronika-notatki/Rok_IV/SDUP/SDUP-FPGA/Lab7/CordicOpt/CordicOpt.sim/sim_1/impl/timing/xsim/xsim.dir/cordic_rtl_TB_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm E:/elektronika-notatki/Rok_IV/SDUP/SDUP-FPGA/Lab7/CordicOpt/CordicOpt.sim/sim_1/impl/timing/xsim/xsim.dir/cordic_rtl_TB_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
